export { AIDetectionSection } from './AIDetectionSection';
export { CarpetSettingsSection } from './CarpetSettingsSection';
export { ConsumablesSection } from './ConsumablesSection';
export { DeviceInfoSection } from './DeviceInfoSection';
export { EdgeCornerSection } from './EdgeCornerSection';
export { FloorSettingsSection } from './FloorSettingsSection';
export { QuickSettingsSection } from './QuickSettingsSection';
export { StationControlsSection } from './StationControlsSection';
export { VolumeSection } from './VolumeSection';
